site_name: VIREON Documentation
site_url: https://github.com/SaadiMalik1/vireon-nvos
site_description: Validation, Integrity, Research Engine for Open Neuro Interfaces
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: cyan
plugins:
  - search
nav:
  - Home: index.md
  - User Guide: user_guide.md
  - Developer Guide: developer_guide.md
  - Plugin SDK: plugin_sdk.md
  - API Reference: api_reference.md
  - Reproducibility Guide: reproducibility_guide.md
