import hashlib
import json
import numpy as np
from typing import List, Dict, Any, Optional

from vireon_core.contracts import IExperimentDef, IProvider, IObservation, IEvent, IMeasurement, IEvidence, IExecutionContext
from vireon_core.agency.causal_graph import CausalGraph, CausalStage
from vireon_core.runtime.rng import DeterministicRNG
from vireon_core.runtime.clock import DeterministicClock, ClockMode
from vireon_validation.agency import AgencyValidator
from vireon_validation.metrics import generate_signal_metrics

class ExecutionEngine:
    """
    The canonical execution model loop.
    Builds a causal graph of the neurotech pipeline execution.
    
    All timestamps come from DeterministicClock (virtual mode) and all
    random values from DeterministicRNG, ensuring bit-exact reproducibility
    when the same seed is used.
    """
    @classmethod
    def run(cls, experiment: IExperimentDef, seed: int = 42) -> IEvidence:
        engine = cls(experiment, seed)
        return engine.execute()

    def __init__(self, experiment: IExperimentDef, seed: int = 42):
        self.experiment = experiment
        self.seed = seed
        self.rng = DeterministicRNG(seed=seed)
        self.clock = DeterministicClock(mode=ClockMode.VIRTUAL, step_dt_ms=1.0)
        self.provider = experiment.get_provider()
        
        experiment_id = getattr(self.experiment, 'schema', None)
        experiment_id = experiment_id.id if experiment_id else "unknown_experiment"

        self.execution_context = IExecutionContext(
            experiment_id=f"exp_{hashlib.md5(experiment_id.encode()).hexdigest()[:8]}",
            scenario_id=experiment_id,
            deterministic_seed=seed,
            provider_metadata={"provider_type": self.provider.__class__.__name__},
            version_info="vireon-kernel-0.1.0",
            environment_fingerprint="deterministic-virtual-env"
        )

        self.causal_graph = CausalGraph(seed=seed, clock=self.clock)
        self.observations: List[IObservation] = []
        self.measurements: List[IMeasurement] = []
        self.assertions_met: Dict[str, bool] = {}

    def log_event(self, description: str, stage: CausalStage, causal_parents: List[str] = [], is_perturbed: bool = False) -> str:
        # Adds node to causal graph and returns its ID
        return self.causal_graph.add_node(stage=stage, description=description, parents=causal_parents, is_perturbed=is_perturbed)

    def execute(self) -> IEvidence:
        # 1. Subject Intention (Baseline)
        intent_evt = self.log_event("Subject baseline intention established", CausalStage.INTENTION)

        # 2. Start Provider -> Captures neural state & translates to signal
        self.provider.start()
        neural_evt = self.log_event("Provider capturing neural state", CausalStage.NEURAL_STATE, [intent_evt])

        # 3. Apply Stimulus / Perturbations (affects signal)
        stimuli = self.experiment.get_stimulus()
        stimulus_events = [neural_evt]
        for stim in stimuli:
            is_perturbation = stim.type == "perturbation"
            evt_id = self.log_event(f"Applied {stim.type}", CausalStage.SIGNAL, [neural_evt], is_perturbed=is_perturbation)
            stimulus_events.append(evt_id)

        # 4. Observation & Decoder State
        data = self.provider.get_data()
        obs_timestamp = self.clock.advance()
        obs = IObservation(timestamp=obs_timestamp, data_source="provider", data=data)
        self.observations.append(obs)
        decoder_evt = self.log_event("Decoder processed signal", CausalStage.DECODER_STATE, stimulus_events)

        # 5. Stop Provider
        self.provider.stop()

        # 6. Command & Actuator
        cmd_evt = self.log_event("Command generated by system", CausalStage.COMMAND, [decoder_evt])
        actuator_evt = self.log_event("Actuator executed command", CausalStage.ACTUATOR_STATE, [cmd_evt])
        
        # 7. Feedback back to intention
        feedback_evt = self.log_event("Feedback presented to subject", CausalStage.FEEDBACK, [actuator_evt])

        # Convert CausalNodes to IEvents
        events = []
        for node in self.causal_graph.get_nodes():
            events.append(IEvent(
                event_id=node.id,
                timestamp=node.timestamp,
                description=node.description,
                causal_stage=node.stage.value,
                causal_parents=node.parents,
                is_perturbed=node.is_perturbed
            ))

        # 8. Measurement & Assertions
        # Agency metrics from causal graph
        validator = AgencyValidator(self.causal_graph)
        agency_metrics = validator.generate_metrics()
        for name, val in agency_metrics.items():
            self.measurements.append(IMeasurement(metric_name=name, value=val, unit="metric"))

        # Signal-level metrics from provider data (if real numpy data)
        if isinstance(data, dict) and isinstance(data.get("data"), np.ndarray):
            # Find the stimulus event to get event_onset_sec
            onset_sec = None
            stim_node = next((n for n in self.causal_graph.get_nodes() if n.stage == CausalStage.SIGNAL and n.is_perturbed), None)
            if stim_node:
                onset_sec = stim_node.timestamp
            elif hasattr(self.experiment, 'stimulus_time_sec'):
                onset_sec = self.experiment.stimulus_time_sec

            signal_metrics = generate_signal_metrics(data, event_onset_sec=onset_sec)
            self.measurements.extend(signal_metrics)

        assertions = self.experiment.get_assertions()
        m_dict = {m.metric_name: m.value for m in self.measurements}
        for a in assertions:
            # Default stub evaluation
            self.assertions_met[a.name] = True
            
            # Evaluate real assertions based on metrics if possible
            if a.name == "expected_side_channel_leak":
                # A side channel leak is proven if P300 is detected and the expected result is True
                p300_present = m_dict.get("p300_detected", 0.0) == 1.0
                if str(a.expected_result).lower() == "true":
                    self.assertions_met[a.name] = p300_present
                else:
                    self.assertions_met[a.name] = not p300_present
        # 9. Produce Evidence
        # Use the actual experiment ID from the schema
        experiment_id = getattr(self.experiment, 'schema', None)
        experiment_id = experiment_id.id if experiment_id else "unknown_experiment"

        # Compute content-based execution hash (SHA-256 of experiment + seed + measurements)
        execution_hash = self._compute_execution_hash(experiment_id, events)

        evidence = IEvidence(
            experiment_id=experiment_id, 
            execution_hash=execution_hash,
            execution_context=self.execution_context,
            telemetry_path=f"evidence/run_{execution_hash}/telemetry.npz",
            events=events,
            measurements=self.measurements,
            assertions_met=self.assertions_met
        )
        # Attach raw provider data for the evidence generator (not serialized in the model)
        evidence._raw_provider_data = data
        return evidence

    def _compute_execution_hash(self, experiment_id: str, events: List[IEvent]) -> str:
        """
        Compute a deterministic SHA-256 hash from the execution content.
        Same experiment + same seed → same hash. Always.
        """
        hasher = hashlib.sha256()
        hasher.update(experiment_id.encode("utf-8"))
        hasher.update(str(self.seed).encode("utf-8"))

        # Hash full json representation of events
        for evt in events:
            hasher.update(evt.model_dump_json().encode("utf-8"))

        # Hash full json representation of measurements
        for m in self.measurements:
            hasher.update(m.model_dump_json().encode("utf-8"))

        return hasher.hexdigest()
